Repository Bird-Lounge/Skyraptor-SS13, pull requests merged in 2023-10, with the labels that each got.

#936 [MIRROR] Removes duplicate icons from belt.dmi
  icons/mob/clothing/belt.dmi
Labels: Upstream PR Merged

#937 [MIRROR] [no gbp] Reduces click cooldown of more primarily player-controlled mobs
  code/modules/mob/living/basic/heretic/heretic_summon.dm
  code/modules/mob/living/basic/space_fauna/morph.dm
  code/modules/mob/living/basic/space_fauna/regal_rat/regal_rat.dm
  code/modules/mob/living/basic/space_fauna/spider/spider.dm
Labels: Upstream PR Merged

#938 [MIRROR] Pulls over some changes I made on wallening
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/visual_helpers.dm
  code/__HELPERS/icon_smoothing.dm
  code/game/atoms.dm
  code/modules/industrial_lift/tram/tram_windows.dm
Labels: Upstream PR Merged

#939 [MIRROR] adds boxes of bandages, and bandages to go in them
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/tools.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes/medical_boxes.dm
  code/game/objects/items/storage/medkit.dm
  code/modules/cargo/goodies.dm
  code/modules/cargo/packs/medical.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/medical/stack_medical.dmi
  icons/obj/storage/box.dmi
Labels: Upstream PR Merged

#940 [MIRROR] Fixes Listening Post Door
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
Labels: Upstream PR Merged

#941 [MIRROR] Fix organs having no DNA and become bloody when violently removed
  code/__DEFINES/surgery.dm
  code/modules/forensics/_forensics.dm
  code/modules/surgery/organs/_organ.dm
  code/modules/surgery/organs/internal/heart/_heart.dm
Labels: Upstream PR Merged

#942 [MIRROR] Tweaks railings to stand and look taller
  code/game/objects/structures/railings.dm
  icons/obj/railings.dmi
Labels: Upstream PR Merged

#943 [MIRROR] Ashwalkers team stores players_spawned via ckeys rather than keys now
  code/modules/mapfluff/ruins/objects_and_mobs/ash_walker_den.dm
  code/modules/mob_spawn/ghost_roles/mining_roles.dm
Labels: Upstream PR Merged

#944 [MIRROR] Kudzu is destroyed by storms
  code/modules/events/space_vines/vine_structure.dm
Labels: Upstream PR Merged

#945 [MIRROR] Adds some solars stuff to the derelict
  _maps/RandomRuins/SpaceRuins/russian_derelict.dmm
Labels: Upstream PR Merged

#946 [MIRROR] Revamps the Beach away mission
  _maps/RandomZLevels/TheBeach.dmm
Labels: Upstream PR Merged

#947 [MIRROR] Add blackout drunk
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_attack.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/mood_events/drug_events.dm
  code/datums/status_effects/debuffs/drunk.dm
  code/modules/reagents/reagent_containers.dm
Labels: Upstream PR Merged

#948 [MIRROR] Fixed spritesheet images for sprite accessories with no icon_state
  code/modules/client/preferences/species_features/basic.dm
Labels: Upstream PR Merged

#949 [MIRROR] Paper bins behave properly when dumping their contents.
  code/modules/paperwork/paperbin.dm
Labels: Upstream PR Merged

#951 [MIRROR] Fixes Lazy Templates fucking over cables, pipes , and shuttles at random
  code/datums/lazy_template.dm
  code/game/turfs/change_turf.dm
  code/modules/mapping/map_template.dm
  code/modules/shuttle/shuttle.dm
Labels: Upstream PR Merged

#952 [MIRROR] `sting_action` `SHOULD_CALL_PARENT`, fixes various stings not blackbox logging
  code/modules/antagonists/changeling/changeling_power.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/antagonists/changeling/powers/biodegrade.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: Upstream PR Merged

#953 [MIRROR] Fix butchered and gibbed mobs to transfer reagents and diseases to meat
  code/datums/components/butchering.dm
  code/modules/food_and_drinks/machinery/gibber.dm
Labels: Upstream PR Merged

#954 [MIRROR] Fixes display of appearance type in VV
  code/__DEFINES/is_helpers.dm
  code/datums/armor/_armor.dm
  code/datums/datumvars.dm
  code/modules/admin/view_variables/debug_variables.dm
Labels: Upstream PR Merged

#955 [MIRROR] Makes dep. order consoles alert the department over radio whenever their cooldown expires
  code/modules/cargo/department_order.dm
Labels: Upstream PR Merged

#956 [MIRROR] Rule Of Cool: Nukie Hallway Mosiac
  _maps/templates/lazy_templates/nukie_base.dmm
Labels: Upstream PR Merged

#957 [MIRROR] Moth death sound & moth wing flutter sound (and emote change)
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/emote.dm
  sound/voice/moth/credit.txt
  sound/voice/moth/moth_death.ogg
  sound/voice/moth/moth_flutter.ogg
Labels: Upstream PR Merged

#958 [MIRROR] Adds tongs
  code/game/objects/items/tongs.dm
  code/modules/cargo/packs/organic.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/research/designs/autolathe/service_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vending/drinnerware.dm
  icons/obj/service/kitchen.dmi
  tgstation.dme
Labels: Upstream PR Merged

#959 [MIRROR] Basic Mob Raw Prophet
  _maps/RandomRuins/SpaceRuins/dangerous_research.dmm
  code/datums/components/focused_attacker.dm
  code/datums/elements/waddling.dm
  code/datums/elements/wheel.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/magic/ascended_shapeshift.dm
  code/modules/mob/living/basic/heretic/heretic_summon.dm
  code/modules/mob/living/basic/heretic/raw_prophet.dm
  code/modules/mob/living/basic/lavaland/watcher/watcher_gaze.dm
  code/modules/mob/living/simple_animal/hostile/heretic_monsters.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/78733_simple_to_basic_raw_prophet.txt
Labels: Upstream PR Merged

#960 [MIRROR] Admin dynamic rule management
  code/__DEFINES/dynamic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_midround_rolling.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Upstream PR Merged

#961 [MIRROR] [MDB Ignore] Audits placement of maintenance helpers in non-maintenance places
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Upstream PR Merged

#933 [MIRROR] The fishing portal generator expansion (plus skill-chip)
  code/__DEFINES/aquarium.dm
  code/__DEFINES/dcs/signals/signals_fish.dm
  code/__DEFINES/experisci.dm
  code/__DEFINES/fish.dm
  code/__DEFINES/fishing.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/components/fishing_spot.dm
  code/datums/mind/skills.dm
  code/datums/skills/_skill.dm
  code/datums/skills/fishing.dm
  code/game/machinery/computer/operating_computer.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/modules/cargo/packs/general.dm
  code/modules/experisci/destructive_scanner.dm
  code/modules/experisci/experiment/experiments.dm
  code/modules/experisci/experiment/handlers/experiment_handler.dm
  code/modules/experisci/experiment/types/experiment.dm
  code/modules/experisci/experiment/types/exploration.dm
  code/modules/experisci/experiment/types/random_scanning.dm
  code/modules/experisci/experiment/types/scanning.dm
  code/modules/experisci/experiment/types/scanning_fish.dm
  code/modules/experisci/experiment/types/scanning_material.dm
  code/modules/experisci/experiment/types/scanning_plants.dm
  code/modules/experisci/handheld_scanner.dm
  code/modules/fishing/aquarium/fish_analyzer.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/fishing/fish/fish_traits.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/fish_catalog.dm
  code/modules/fishing/fishing_equipment.dm
  code/modules/fishing/fishing_minigame.dm
  code/modules/fishing/fishing_portal_machine.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/fishing/sources/_fish_source.dm
  code/modules/fishing/sources/source_types.dm
  code/modules/library/skill_learning/skillchip.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/unit_tests/fish_unit_tests.dm
  code/modules/vending/games.dm
  icons/hud/fishing_hud.dmi
  icons/hud/radial_fishing.dmi
  icons/obj/aquarium.dmi
  icons/obj/fishing.dmi
  sound/attributions.txt
  sound/effects/arcade_jump.ogg
  sound/effects/boing.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/ExperimentConfigure.js
Labels: Upstream PR Merged

#966 [MIRROR] The Galactic Materials Market no longer runtimes on opening or ordering.
  code/modules/cargo/exports/materials.dm
  code/modules/cargo/materials_market.dm
Labels: Upstream PR Merged

#967 [MIRROR] Adds a passive scan to the Active Sonar module
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mod/modules/modules_security.dm
Labels: Upstream PR Merged

#969 [MIRROR] gibbing ghosts you before you get deleted by gibbing
  code/modules/mob/living/death.dm
Labels: Upstream PR Merged

#970 [MIRROR] Basic Mob Flesh Worm
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/datums/components/cult_ritual_item.dm
  code/datums/components/mob_chain.dm
  code/datums/components/rot.dm
  code/datums/elements/amputating_limbs.dm
  code/datums/wounds/_wounds.dm
  code/game/objects/items/devices/polycircuit.dm
  code/modules/admin/admin_verbs.dm
  code/modules/antagonists/cult/cult_bastard_sword.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/heretic/magic/flesh_ascension.dm
  code/modules/antagonists/heretic/structures/knock_final.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/basic/health_adjustment.dm
  code/modules/mob/living/basic/heretic/flesh_worm.dm
  code/modules/mob/living/basic/lavaland/lobstrosity/lobstrosity.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/heretic_monsters.dm
  code/modules/pai/defense.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/mob_chains.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
Labels: Upstream PR Merged

#972 [MIRROR] Codeowner adjustment
  .github/CODEOWNERS
Labels: Upstream PR Merged

#973 [MIRROR] MetaStation disposals fix
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Upstream PR Merged

#974 [MIRROR] Engineering Borgs can no longer grab their own iron module
  code/game/objects/items/robot/items/storage.dm
Labels: Upstream PR Merged

#976 [MIRROR] Fixes an issue with COMSIG_MOB_ABILITY_STARTED for spells
  code/modules/spells/spell.dm
Labels: Upstream PR Merged

#977 [MIRROR] Fake moustaches are now poorly slapped on top of what you're wearing
  code/modules/clothing/masks/moustache.dm
Labels: Upstream PR Merged

#979 [MIRROR] The AI can no longer turn off shapeshifted robots
  code/modules/spells/spell_types/shapeshift/_shapeshift.dm
Labels: Upstream PR Merged

#980 [MIRROR] Fixes the HEAL_NEGATIVE_MUTATIONS revive flag
  code/modules/mob/living/carbon/human/human.dm
Labels: Upstream PR Merged

#981 [MIRROR] Adds sanity checking to the tippable component
  code/datums/components/tippable.dm
Labels: Upstream PR Merged

#982 [MIRROR] Refactors Goats into Basic Mobs
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/datums/memory/_memory.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/events/ghost_role/sentience.dm
  code/modules/events/wizard/petsplosion.dm
  code/modules/mob/living/basic/farm_animals/goat/_goat.dm
  code/modules/mob/living/basic/farm_animals/goat/goat_ai.dm
  code/modules/mob/living/basic/farm_animals/goat/goat_subtypes.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/78759_simple_to_basic_goat.txt
Labels: Upstream PR Merged

#984 [MIRROR] QoL improvements to the mob damage unit tests
  code/modules/unit_tests/mob_damage.dm
Labels: Upstream PR Merged

#985 [MIRROR] Bad food has bad food reagent again
  code/datums/components/bakeable.dm
  code/datums/components/grillable.dm
  code/datums/elements/food/microwavable.dm
Labels: Upstream PR Merged

#987 [MIRROR] fish analyzers can also be used to perform fish scanning experiments.
  code/__DEFINES/dcs/signals/signals_fish.dm
  code/modules/cargo/goodies.dm
  code/modules/cargo/packs/general.dm
  code/modules/fishing/aquarium/fish_analyzer.dm
Labels: Upstream PR Merged

#988 [MIRROR] Organ harvester file cleanup
  code/game/machinery/harvester.dm
Labels: Upstream PR Merged

#989 [MIRROR] Makes the Regal Condor realistically simulate being shot dead with a high caliber hand cannon by making it HITSCAN
  code/datums/components/crafting/ranged_weapon.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Upstream PR Merged

#990 [MIRROR] Jungle-Generator Usability Fixes, Geode Patchups
  _maps/shuttles/pirate_geode.dmm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/planet.dm
Labels: Upstream PR Merged

#991 [MIRROR] The laser carbine, a full-auto sidegrade to the normal laser gun
  code/datums/components/fullauto.dm
  code/modules/cargo/packs/security.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/weapons/guns/energy.dmi
  icons/obj/weapons/guns/projectiles.dmi
Labels: Upstream PR Merged

#992 [MIRROR] Kills `spec_updatehealth`, replaces it with use of `COMSIG_LIVING_HEALTH_UPDATE`
  code/modules/admin/create_mob.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Upstream PR Merged

#993 [MIRROR] offical to official
  code/game/objects/items/tail_pin.dm
  code/modules/admin/verbs/admin_newscaster.dm
  code/modules/art/paintings.dm
  config/blanks.json
  tgui/packages/tgui/interfaces/AdminFax.js
  tools/ci/check_grep.sh
Labels: Upstream PR Merged

#994 [MIRROR] Frosty's factions are now defines
  code/modules/mob/living/basic/space_fauna/statue/statue.dm
Labels: Upstream PR Merged

#995 [MIRROR] also removes exodrone adventures from prefixed sql schema
  SQL/tgstation_schema_prefixed.sql
Labels: Upstream PR Merged

#997 [MIRROR] allows janitor keys to be stored in janitor wintercoats and janibets
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/wintercoats.dm
Labels: Upstream PR Merged

#998 [MIRROR] adds directional helpers for empty fire axe and mech removal crowbar cabinets
  code/game/objects/structures/fireaxe.dm
  tools/UpdatePaths/Scripts/78722_empty_fireaxe_cabinet_directionals.txt
Labels: Upstream PR Merged

#999 [MIRROR] Dogs now flee from mobs with tongs
  code/datums/ai/basic_mobs/targetting_datums/with_object.dm
  code/datums/ai/dog/dog_controller.dm
  tgstation.dme
Labels: Upstream PR Merged

#1000 [MIRROR] fixed wierd TGUI crash
  tgui/packages/tgui/interfaces/NtosMessenger/index.tsx
Labels: Upstream PR Merged

#1002 [MIRROR] Fix ID card examine runtime
  code/game/objects/items/cards_ids.dm
Labels: Upstream PR Merged

#1003 [MIRROR] Added slapcrafting to tech shells
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
Labels: Upstream PR Merged

#1004 [MIRROR] Renames prison intercoms
  code/game/objects/items/devices/radio/intercom.dm
Labels: Upstream PR Merged

#1005 [MIRROR] Tendril Tagging - scanning necropolis tendrils with a mining analyzer updates its GPS tag
  code/game/objects/structures/icemoon/cave_entrance.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/game/objects/structures/spawner.dm
Labels: Upstream PR Merged

#1006 [MIRROR] Refactors Sloths into Basic Mobs
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/datums/ai/basic_mobs/basic_subtrees/climb_tree.dm
  code/datums/components/tree_climber.dm
  code/datums/station_traits/neutral_traits.dm
  code/modules/antagonists/traitor/objectives/kill_pet.dm
  code/modules/events/ghost_role/sentience.dm
  code/modules/events/wizard/petsplosion.dm
  code/modules/mob/living/basic/pets/sloth.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/78752_simple_to_basic_sloths.txt
Labels: Upstream PR Merged

#543 [MIRROR] Fixes implanted legion cores being available for use when dead/unconscious
  code/__DEFINES/actions.dm
  code/datums/actions/action.dm
  code/modules/mining/equipment/monster_organs/monster_organ.dm
  code/modules/mining/equipment/monster_organs/regenerative_core.dm
Labels: Do Not Merge, Needs Something, Upstream PR Merged

#632 [MIRROR] Updates chem factory tank sprites
  icons/obj/pipes_n_cables/hydrochem/plumbers.dmi
Labels: Needs Something, Upstream PR Merged

#793 [MIRROR] Fixes Boneless Smite
  code/modules/admin/smites/boneless.dm
Labels: Upstream PR Merged

#1012 [MIRROR] Camera consoles no longer constantly check camera list
  code/game/machinery/computer/camera.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  tgui/packages/tgui/interfaces/CameraConsole.tsx
Labels: Upstream PR Merged

#1011 [MIRROR] Spider Type Check Fix
  code/__DEFINES/is_helpers.dm
  code/game/objects/effects/spiderwebs.dm
Labels: Upstream PR Merged

#1009 [MIRROR] Separates COMSIG_LIVING_ADJUST_DAMAGE into 6 different signals
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/datums/components/mob_chain.dm
  code/modules/mob/living/basic/health_adjustment.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/pai/defense.dm
  code/modules/pai/pai.dm
Labels: Upstream PR Merged

#1008 [MIRROR] Fix bodies burning or set on fire while husked
  code/datums/status_effects/debuffs/fire_stacks.dm
Labels: Upstream PR Merged

#1007 [MIRROR] People who are bald can still grow a beard with barber aid
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Upstream PR Merged

#935 [MIRROR] Revert font scaling in TGUI chat back to its prior implementation
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/middleware.js
  tgui/packages/tgui-panel/settings/reducer.js
Labels: Upstream PR Merged

#932 [MIRROR] Security Officers can now Download the Plexagon Crew Manifest PDA App
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
Labels: Upstream PR Merged

#1013 [MIRROR] ice demon basic mobs
  code/__DEFINES/ai/monsters.dm
  code/datums/ai/basic_mobs/basic_subtrees/maintain_distance.dm
  code/datums/ai/basic_mobs/basic_subtrees/ranged_skirmish.dm
  code/datums/ai/basic_mobs/basic_subtrees/teleport_away_from_target.dm
  code/datums/ai/hunting_behavior/hunting_behaviors.dm
  code/datums/components/joint_damage.dm
  code/datums/mapgen/Cavegens/IcemoonCaves.dm
  code/game/objects/structures/icemoon/cave_entrance.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/basic/icemoon/ice_demon/ice_demon.dm
  code/modules/mob/living/basic/icemoon/ice_demon/ice_demon_abilities.dm
  code/modules/mob/living/basic/icemoon/ice_demon/ice_demon_ai.dm
  code/modules/mob/living/basic/lavaland/watcher/watcher_ai.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_demon.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  icons/obj/mining_zones/artefacts.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/78539_ice_demons.txt
Labels: Upstream PR Merged

#1014 [MIRROR] Fixes Slaughter/Laughter Demon Melee Cooldowns
  code/modules/mob/living/basic/space_fauna/demon/demon.dm
Labels: Upstream PR Merged

#1015 [MIRROR] Supermatter shards can be unfastened with right click
  code/datums/components/supermatter_crystal.dm
Labels: Upstream PR Merged

#1016 [MIRROR] Fixes pete's examine runtime
  code/modules/mob/living/basic/farm_animals/goat/goat_subtypes.dm
Labels: Upstream PR Merged

#1017 [MIRROR] Uplink Item Reputation Audit
  code/modules/uplink/uplink_items/ammunition.dm
  code/modules/uplink/uplink_items/badass.dm
  code/modules/uplink/uplink_items/bundle.dm
  code/modules/uplink/uplink_items/dangerous.dm
  code/modules/uplink/uplink_items/explosive.dm
  code/modules/uplink/uplink_items/job.dm
  code/modules/uplink/uplink_items/stealthy.dm
Labels: Upstream PR Merged

#1018 [MIRROR] Fixes setting prebuilt shutter ids with multiool
  code/game/machinery/doors/poddoor.dm
Labels: Upstream PR Merged

#1019 [MIRROR] Fixes bioscramble picking base wing type
  code/__DEFINES/research/anomalies.dm
Labels: Upstream PR Merged

#1020 [MIRROR] Improves many areas of CentCom
  _maps/map_files/generic/CentCom.dmm
Labels: Upstream PR Merged

#1021 [MIRROR] Fixed Meta disposals.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Upstream PR Merged

#1022 [MIRROR] Reviver Implant will actually revive people!
  code/modules/surgery/organs/internal/cyberimp/augments_chest.dm
Labels: Upstream PR Merged

#1023 [MIRROR] General code maintenance for Reagents
  code/__DEFINES/reagents.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/lists/reagents.dm
  code/game/objects/items/food/moth.dm
  code/modules/reagents/chemistry/equilibrium.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  tgstation.dme
Labels: Upstream PR Merged

#1024 [MIRROR] Adds supermatter attackby_hit typecache to deal with similarly-handled objects
  code/datums/components/supermatter_crystal.dm
Labels: Upstream PR Merged

#1025 [MIRROR] Bitrunning hotfix 3
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/dcs/signals/signals_bitrunning.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/modules/bitrunning/components/avatar_connection.dm
  code/modules/bitrunning/designs.dm
  code/modules/bitrunning/objects/byteforge.dm
  code/modules/bitrunning/objects/host_monitor.dm
  code/modules/bitrunning/objects/landmarks.dm
  code/modules/bitrunning/objects/netpod.dm
  code/modules/bitrunning/objects/vendor.dm
  code/modules/bitrunning/server/loot.dm
  code/modules/bitrunning/server/map_handling.dm
  code/modules/bitrunning/server/quantum_server.dm
  code/modules/bitrunning/server/util.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/bitrunning.dm
  icons/obj/machines/bitrunning.dmi
  tgstation.dme
Labels: Upstream PR Merged

#1026 [MIRROR] Dels a bad stack trace from stoned effect
  code/datums/status_effects/drug_effects.dm
Labels: Upstream PR Merged

#1028 [MIRROR] Fixes salt, flour, corn starch, and saltwater not sanity checking exposed mobs
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Upstream PR Merged

#1029 [MIRROR] Fixes void cloak not making suit store slot items unstrippable
  code/modules/antagonists/heretic/items/heretic_armor.dm
Labels: Upstream PR Merged

#1030 [MIRROR] Fixes camera ref cleanup in alarms processing
  code/datums/alarm.dm
Labels: Upstream PR Merged

#1031 [MIRROR] Fixes runtime on initalizing science programs
  code/controllers/subsystem/research.dm
  code/modules/modular_computers/file_system/programs/frontier.dm
  code/modules/modular_computers/file_system/programs/techweb.dm
Labels: Upstream PR Merged

#1032 [MIRROR] Fix TTS runtime from wearing bread
  code/modules/mob/living/living_say.dm
Labels: Upstream PR Merged

#1033 [MIRROR] Fix bitrunning drinking glass using the wrong subtype
  _maps/virtual_domains/beach_bar.dmm
  code/modules/bitrunning/virtual_domain/domains/beach_bar.dm
Labels: Upstream PR Merged

#1034 [MIRROR] Warm donk-pockets once again have omnizine in them
  code/datums/components/bakeable.dm
  code/datums/components/grillable.dm
  code/datums/elements/food/microwavable.dm
  code/game/objects/items/food/donkpocket.dm
  code/game/objects/items/food/packaged.dm
Labels: Upstream PR Merged

#1036 [MIRROR] changes COMSIG_GLOB_LIGHT_MECHANISM_COMPLETED into a more versatile signal
  code/__DEFINES/dcs/signals/signals_global.dm
  code/game/objects/items/puzzle_pieces.dm
Labels: Upstream PR Merged

#1037 [MIRROR] [NO GBP] you can hit tendrils in melee again
  code/game/objects/structures/spawner.dm
Labels: Upstream PR Merged

#1038 [MIRROR] Prevent a runtime in malf AI's overload machine ability when it runs out of uses
  code/modules/antagonists/malf_ai/malf_ai_modules.dm
Labels: Upstream PR Merged

#1039 [MIRROR] Fixes fleeing behaviour
  code/__DEFINES/ai/ai_blackboard.dm
  code/datums/ai/basic_mobs/basic_ai_behaviors/run_away_from_target.dm
  code/datums/ai/basic_mobs/basic_subtrees/flee_target.dm
  code/datums/ai/basic_mobs/basic_subtrees/simple_find_nearest_target_to_flee.dm
  code/datums/ai/dog/dog_controller.dm
  code/datums/elements/ai_flee_while_injured.dm
  code/modules/mob/living/basic/farm_animals/deer.dm
  code/modules/mob/living/basic/farm_animals/rabbit.dm
  code/modules/mob/living/basic/farm_animals/sheep.dm
  code/modules/mob/living/basic/jungle/mega_arachnid/mega_arachnid_ai.dm
  code/modules/mob/living/basic/lavaland/goldgrub/goldgrub_ai.dm
  code/modules/mob/living/basic/lavaland/legion/legion_ai.dm
  code/modules/mob/living/basic/lavaland/lobstrosity/lobstrosity.dm
  code/modules/mob/living/basic/lavaland/lobstrosity/lobstrosity_ai.dm
  code/modules/mob/living/basic/pets/fox.dm
  code/modules/mob/living/basic/space_fauna/carp/carp_ai_rift_actions.dm
  code/modules/mob/living/basic/space_fauna/carp/carp_controllers.dm
  code/modules/mob/living/basic/space_fauna/regal_rat/regal_rat_ai.dm
  code/modules/mob/living/basic/space_fauna/spider/giant_spider/giant_spider_ai.dm
  code/modules/mob/living/basic/space_fauna/spider/spiderlings/spiderling.dm
  code/modules/mob/living/basic/space_fauna/wumborian_fugu/inflation.dm
  code/modules/mob/living/basic/space_fauna/wumborian_fugu/wumborian_ai.dm
  code/modules/mob/living/basic/vermin/crab.dm
  code/modules/mob/living/basic/vermin/mouse.dm
Labels: Upstream PR Merged

#1041 [MIRROR] Fixes some EMP'd cyborg bodypart runtimes
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
Labels: Upstream PR Merged

#1042 [MIRROR] Autopsy scanners fit in surgery trays
  code/datums/storage/subtypes/surgery_tray.dm
  code/game/objects/items/surgery_tray.dm
Labels: Upstream PR Merged

#1043 [MIRROR] Fix virtual gondola meat
  code/modules/bitrunning/virtual_domain/domains/gondola_asteroid.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Upstream PR Merged

#1044 [MIRROR] Refactors Revenants into Basic Mobs
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/chat.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/phobias.dm
  code/datums/components/blob_minion.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/events/ghost_role/revenant_event.dm
  code/modules/jobs/job_types/chaplain/chaplain_nullrod.dm
  code/modules/library/bibles.dm
  code/modules/mob/living/basic/space_fauna/revenant/_revenant.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_abilities.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_effects.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_harvest.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_items.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_objectives.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/revenant.dm
  code/modules/mob/mob_movement.dm
  code/modules/photography/camera/other.dm
  code/modules/projectiles/guns/ballistic/bows/bow_arrows.dm
  code/modules/projectiles/guns/ballistic/bows/bow_types.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/religion/burdened/psyker.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
Labels: Upstream PR Merged

#1045 [MIRROR] Adds a cowboy bundle to the nuclear ops uplink
  code/datums/greyscale/config_types/greyscale_configs/greyscale_mobs.dm
  code/datums/greyscale/json_configs/pony.json
  code/game/machinery/syndicatebeacon.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/head/hat.dm
  code/modules/clothing/shoes/cowboy.dm
  code/modules/clothing/under/costume.dm
  code/modules/mob/living/basic/farm_animals/pony.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/uplink/uplink_items/nukeops.dm
  icons/mob/simple/animal.dmi
  sound/effects/footstep/spurs1.ogg
  sound/effects/footstep/spurs2.ogg
  sound/effects/footstep/spurs3.ogg
Labels: Upstream PR Merged

#1047 [MIRROR] Replaces the changeling spacesuit with a passive ability
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling_power.dm
  code/modules/antagonists/changeling/powers/defib_grasp.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/void_adaption.dm
  code/modules/meteors/meteor_spawning.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/unit_tests/screenshots/screenshot_antag_icons_changelingmidround.png
  tgstation.dme
Labels: Upstream PR Merged

#1049 [MIRROR] makes unholy water an effective coagulant for cultists
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Upstream PR Merged

#1050 [MIRROR] fixes polymorphing into a holoparasite
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Upstream PR Merged

#1051 [MIRROR] Borg modules can no longer be sold by pirates
  code/modules/antagonists/pirate/pirate_shuttle_equipment.dm
  code/modules/cargo/exports.dm
Labels: Upstream PR Merged

#1052 [MIRROR] Fixes an issue w/ antiglow.
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
  code/datums/mutations/body.dm
Labels: Upstream PR Merged

#1053 [MIRROR] Camera UI fixes
  tgui/packages/tgui/interfaces/CameraConsole.tsx
Labels: Upstream PR Merged

#1054 [MIRROR] [NO GBP] ACTUALLY fixes wound replacement removing gauze
  code/datums/wounds/_wounds.dm
  code/datums/wounds/bones.dm
Labels: Upstream PR Merged

#1055 [MIRROR] Add burning sound loop to bonfires and fireplaces
  code/datums/looping_sounds/burning.dm
  code/game/objects/structures/bonfire.dm
  code/game/objects/structures/fireplace.dm
  tgstation.dme
Labels: Upstream PR Merged

#1056 [MIRROR] [no gbp] Disable summon AI during summoning
  code/modules/antagonists/heretic/heretic_knowledge.dm
Labels: Upstream PR Merged

#1058 [MIRROR] Relocates a garbage spawner on Tramstation that was causing rng CI failures
  _maps/map_files/tramstation/tramstation.dmm
Labels: Upstream PR Merged

#1060 [MIRROR] Basic Constructs: parent type + Harvester
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/__DEFINES/is_helpers.dm
  code/_globalvars/phobias.dm
  code/datums/components/healing_touch.dm
  code/datums/elements/amputating_limbs.dm
  code/datums/elements/structure_repair.dm
  code/datums/elements/wall_walker.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/walls.dm
  code/modules/mob/living/basic/constructs/_construct.dm
  code/modules/mob/living/basic/constructs/harvester.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/constructs/constructs.dm
  code/modules/mob/transform_procs.dm
  code/modules/power/singularity/narsie.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/78807_simple_to_basic_construct_harvester.txt
Labels: Upstream PR Merged

#1061 [MIRROR] Fixes some issues with mirrors not updating mob appearance after making a selection
  code/game/objects/structures/mirror.dm
Labels: Upstream PR Merged

#1062 [MIRROR] Adds bitrunner to the crew monitor
  code/game/machinery/computer/crew.dm
Labels: Upstream PR Merged

#1063 [MIRROR] Adds a base physical description proc to gameplay species, displays it on magic mirrors.
  code/game/objects/structures/mirror.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/snail.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Upstream PR Merged

#1064 [MIRROR] Fix outdated research connections from the Lionhunter's Rifle and Rust Charge
  code/modules/antagonists/heretic/knowledge/blade_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/side_blade_rust.dm
Labels: Upstream PR Merged

#1065 [MIRROR] Adds practice carbines to all firing ranges
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/templates/holodeck_firingrange.dmm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Upstream PR Merged

#1067 [MIRROR] Adds several new sound effects for the blood cult
  code/datums/components/cult_ritual_item.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/cult_team.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/hallucination/fake_sound.dm
  code/modules/hallucination/station_message.dm
  sound/ambience/antag/bloodcult/bloodcult_eyes.ogg
  sound/ambience/antag/bloodcult/bloodcult_gain.ogg
  sound/ambience/antag/bloodcult/bloodcult_halos.ogg
  sound/ambience/antag/bloodcult/bloodcult_scribe.ogg
Labels: Upstream PR Merged

#1068 [MIRROR] Galactic Market Hot Fixes
  code/modules/cargo/materials_market.dm
  code/modules/cargo/packs/stock_market_items.dm
  tgui/packages/tgui/interfaces/MatMarket.tsx
Labels: Upstream PR Merged

#1069 [MIRROR] Allows you to choose between three lipstick styles
  code/game/objects/items/cosmetics.dm
  icons/hud/radial.dmi
  icons/mob/human/human_face.dmi
Labels: Upstream PR Merged

#1070 [MIRROR] Flesh Spiders Regenerate + QoL
  code/game/objects/effects/spiderwebs.dm
  code/modules/antagonists/spiders/spiders.dm
  code/modules/mob/living/basic/space_fauna/changeling/flesh_spider.dm
  code/modules/mob/living/basic/space_fauna/changeling/headslug.dm
  code/modules/mob/living/basic/space_fauna/spider/giant_spider/giant_spiders.dm
  code/modules/mob_spawn/ghost_roles/spider_roles.dm
  tgstation.dme
Labels: Upstream PR Merged

#1071 [MIRROR] venus human traps are basicmobs + ""balance""
  code/modules/mob/living/basic/jungle/venus_human_trap.dm
  code/modules/mob_spawn/ghost_roles/venus_human_trap.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
Labels: Upstream PR Merged

#1077 [MIRROR] Pharmacy map fixes
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Upstream PR Merged

#1076 [MIRROR] Watcher Nest Lavaland Ruin
  _maps/RandomRuins/LavaRuins/lavaland_surface_watcher_grave.dmm
  code/datums/components/temporary_description.dm
  code/datums/ruins/lavaland.dm
  code/game/objects/items/food/_food.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/food/packaged.dm
  code/game/objects/items/food/soup.dm
  code/game/turfs/closed/indestructible.dm
  code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
  code/modules/mapfluff/ruins/lavalandruin_code/watcher_grave.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob_spawn/corpses/nonhuman_corpses.dm
  code/modules/mob_spawn/mob_spawn.dm
  code/modules/projectiles/projectile.dm
  config/lavaruinblacklist.txt
  icons/mob/simple/lavaland/lavaland_monsters_wide.dmi
  icons/obj/food/egg.dmi
  tgstation.dme
Labels: Upstream PR Merged

#1075 [MIRROR] Basic Mob Gorillas
  code/__DEFINES/ai/ai_blackboard.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_main.dm
  code/__DEFINES/drone.dm
  code/__DEFINES/guardian_defines.dm
  code/datums/ai/basic_mobs/basic_subtrees/run_emote.dm
  code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
  code/datums/components/basic_inhands.dm
  code/datums/elements/amputating_limbs.dm
  code/datums/memory/_memory.dm
  code/datums/station_traits/neutral_traits.dm
  code/game/objects/items/food/monkeycube.dm
  code/modules/antagonists/traitor/objectives/kill_pet.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/basic/clown/clown.dm
  code/modules/mob/living/basic/farm_animals/gorilla/gorilla.dm
  code/modules/mob/living/basic/farm_animals/gorilla/gorilla_accessories.dm
  code/modules/mob/living/basic/farm_animals/gorilla/gorilla_ai.dm
  code/modules/mob/living/basic/farm_animals/gorilla/gorilla_emotes.dm
  code/modules/mob/living/basic/heretic/flesh_worm.dm
  code/modules/mob/living/basic/lavaland/lobstrosity/lobstrosity.dm
  code/modules/mob/living/carbon/alien/adult/adult_update_icons.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/visuals_icons.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/visuals_icons.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_update_icons.dm
  code/modules/mob/transform_procs.dm
  code/modules/spells/spell_types/conjure/simian.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  strings/sillytips.txt
  tgstation.dme
  tools/UpdatePaths/Scripts/78918_simple_to_basic_gorilla.txt
Labels: Upstream PR Merged

#1074 [MIRROR] [NO GBP] Fixed a few more issues with fishing.
  code/modules/experisci/experiment/types/scanning_fish.dm
  code/modules/fishing/fishing_minigame.dm
Labels: Upstream PR Merged

#1073 [MIRROR] Microwave upgrades: Microwave PDA charging, power cells
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/wires.dm
  code/datums/wires/microwave.dm
  code/game/objects/effects/spawners/random/decoration.dm
  code/game/objects/effects/spawners/random/techstorage.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/game/objects/items/rcd/RCD.dm
  code/game/objects/structures/showcase.dm
  code/game/turfs/open/floor.dm
  code/modules/asset_cache/assets/rcd.dm
  code/modules/food_and_drinks/machinery/microwave.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/machines/microwave.dmi
  strings/tips.txt
Labels: Upstream PR Merged

#1057 [MIRROR] Fixes a runtime in obj/item/organ/on_death()
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/organs/internal/cyberimp/augments_chest.dm
Labels: Upstream PR Merged

#270 [SEMI-MODULAR] Species Work Part the 4nd
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  modular_skyraptor/modules/aesthetics/daedmoth/code/daedmoth.dm
  modular_skyraptor/modules/aesthetics/daedmoth/icons/bodyparts.dmi
  modular_skyraptor/modules/aesthetics/daedmoth/icons/eyes.dmi
  modular_skyraptor/modules/aesthetics/digiclothes/ported_under.dm
  modular_skyraptor/modules/newemotes/newemotes_normal.dm
  modular_skyraptor/modules/newemotes/sounds/voice/feline_purr.ogg
  modular_skyraptor/modules/species_akula/code/akula_features.dm
  modular_skyraptor/modules/species_slugcat/code/scug_features.dm
  modular_skyraptor/modules/species_talonmoth/code/talonmoth_features.dm
  modular_skyraptor/modules/species_talonmoth/icons/bodyparts.dmi
  modular_skyraptor/modules/species_talonmoth/icons/talonmoth_external.dmi
  modular_skyraptor/modules/species_teshvali/code/avalari_bodyparts.dm
  modular_skyraptor/modules/species_teshvali/code/avalari_features.dm
  modular_skyraptor/modules/species_teshvali/code/teshvali_bodyparts.dm
  modular_skyraptor/modules/species_teshvali/code/teshvali_features.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
Labels: Feature, Fix

#1079 [MIRROR] Updates the rollerdrome
  _maps/shuttles/emergency_rollerdome.dmm
Labels: Upstream PR Merged

#1080 [MIRROR] Fixes blast door controllers not working correctly
  code/game/machinery/doors/poddoor.dm
Labels: Upstream PR Merged

#1081 [MIRROR] Fixes passing in list arguments in callproc
  code/modules/admin/callproc/callproc.dm
Labels: Upstream PR Merged

#1082 [MIRROR] Remove tiered canister construction
  _maps/RandomRuins/IceRuins/icemoon_underground_abandoned_plasma_facility.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/infested_frigate.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/russian_derelict.dmm
  _maps/map_files/Birdshot/birdshot.dmm
  _maps/map_files/NorthStar/north_star.dmm
  code/game/machinery/canister_frame.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/fluff.dm
  icons/obj/fluff/general.dmi
  icons/obj/pipes_n_cables/atmos.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/78909_tiered_canister_removal.txt
Labels: Upstream PR Merged

#1083 [MIRROR] basicmobs that qdel on death ghost before qdel
  code/modules/mob/living/basic/basic.dm
Labels: Upstream PR Merged

#1086 [MIRROR] General code maintenance for rcd devices and their DEFINE file
  code/__DEFINES/colors.dm
  code/__DEFINES/construction.dm
  code/__DEFINES/construction/actions.dm
  code/__DEFINES/construction/material.dm
  code/__DEFINES/construction/rcd.dm
  code/__DEFINES/construction/structures.dm
  code/__DEFINES/crafting.dm
  code/__HELPERS/construction.dm
  code/_globalvars/lists/crafting.dm
  code/_globalvars/lists/rcd.dm
  code/_globalvars/rcd.dm
  code/game/atoms.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/firealarm.dm
  code/game/objects/effects/rcd.dm
  code/game/objects/items/rcd/RCD.dm
  code/game/objects/items/rcd/RHD.dm
  code/game/objects/items/rcd/RLD.dm
  code/game/objects/items/rcd/RPLD.dm
  code/game/objects/items/rcd/RTD.dm
  code/game/objects/structures/construction_console/construction_actions.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/reflector.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/misc.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/modules/asset_cache/assets/rcd.dm
  code/modules/atmospherics/machinery/air_alarm/air_alarm_interact.dm
  code/modules/power/apc/apc_tool_act.dm
  code/modules/power/floodlight.dm
  code/modules/unit_tests/rcd.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/RapidConstructionDevice.tsx
  tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx
  tgui/packages/tgui/interfaces/RapidPlumbingDevice.tsx
Labels: Upstream PR Merged

#1087 [MIRROR] Dullahan Fixes
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
Labels: Upstream PR Merged

#1089 [MIRROR] Basic Space Dragon
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/__DEFINES/explosions.dm
  code/__DEFINES/megafauna.dm
  code/__DEFINES/traits.dm
  code/datums/actions/mobs/fire_breath.dm
  code/datums/actions/mobs/mobcooldown.dm
  code/datums/actions/mobs/sneak.dm
  code/datums/components/pry_open_door.dm
  code/datums/components/torn_wall.dm
  code/datums/elements/door_pryer.dm
  code/datums/elements/wall_tearer.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items/devices/laserpointer.dm
  code/game/objects/items/dna_probe.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/false_walls.dm
  code/game/turfs/open/floor/plating.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/events/ghost_role/space_dragon.dm
  code/modules/holodeck/turfs.dm
  code/modules/mob/living/basic/icemoon/ice_whelp/ice_whelp.dm
  code/modules/mob/living/basic/icemoon/ice_whelp/ice_whelp_abilities.dm
  code/modules/mob/living/basic/lavaland/brimdemon/brimbeam.dm
  code/modules/mob/living/basic/lavaland/goliath/goliath_actions.dm
  code/modules/mob/living/basic/lavaland/hivelord/spawn_hivelord_brood.dm
  code/modules/mob/living/basic/lavaland/legion/spawn_legions.dm
  code/modules/mob/living/basic/lavaland/watcher/watcher_gaze.dm
  code/modules/mob/living/basic/lavaland/watcher/watcher_overwatch.dm
  code/modules/mob/living/basic/space_fauna/faithless.dm
  code/modules/mob/living/basic/space_fauna/regal_rat/regal_rat.dm
  code/modules/mob/living/basic/space_fauna/space_dragon/dragon_breath.dm
  code/modules/mob/living/basic/space_fauna/space_dragon/dragon_gust.dm
  code/modules/mob/living/basic/space_fauna/space_dragon/space_dragon.dm
  code/modules/mob/living/basic/space_fauna/spider/spider_abilities/lay_eggs.dm
  code/modules/mob/living/basic/space_fauna/spider/spider_abilities/web.dm
  code/modules/mob/living/basic/space_fauna/spider/spider_abilities/wrap.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/research/server.dm
  code/modules/unit_tests/dragon_expiration.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/78979_simple_to_basic_space_dragon.txt
Labels: Upstream PR Merged

#1090 [MIRROR] Miscellaneous Robotic Limb Fixes
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm
  code/__DEFINES/traits.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  code/modules/surgery/organ_manipulation.dm
Labels: Upstream PR Merged

#1091 [MIRROR] Improved documentation and message for the dcs_check_list_arguments unit test.
  code/__DEFINES/dcs/flags.dm
  code/modules/unit_tests/dcs_check_list_arguments.dm
Labels: Upstream PR Merged

#1092 [MIRROR] Adds blackbox logging to Dynamic setup_parameters proc.
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Upstream PR Merged

#1093 [MIRROR] Allows spacemen to use age-appropriate drugs by making it so you can now huff N2O to get high.
  code/modules/surgery/organs/internal/lungs/_lungs.dm
Labels: Upstream PR Merged

#1094 [MIRROR] Makes riot helmet more consistent with other sec helmets
  code/modules/clothing/head/helmet.dm
Labels: Upstream PR Merged

#1095 [MIRROR] Fixes Monkey's Delight recipe no good boy point
  code/modules/food_and_drinks/recipes/soup_mixtures.dm
Labels: Upstream PR Merged

#1096 [MIRROR] Overclocked Vent Pumps
  code/datums/looping_sounds/vents.dm
  code/game/atom_defense.dm
  code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  icons/obj/machines/atmospherics/unary_devices.dmi
  sound/machines/fan_break.ogg
  sound/machines/fan_loop.ogg
  sound/machines/fan_start.ogg
  sound/machines/fan_stop.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/common/AtmosControls.tsx
Labels: Upstream PR Merged

#1097 [MIRROR] Bladists can now use silver *or* titanium while creating their blades
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/knowledge/blade_lore.dm
Labels: Upstream PR Merged

#1088 [MIRROR] Fixes leaning runtiming from non-carbon mobs, adds a slight animation to the effect
  code/_globalvars/traits.dm
  code/game/turfs/closed/walls.dm
  code/modules/mob/living/carbon/carbon_defines.dm
Labels: Upstream PR Merged

#1098 [MIRROR] Gets some of the easy-bad species procs
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/zombie/organs.dm
Labels: Upstream PR Merged

#1100 [MIRROR] [NO GBP]Fixes plumbing for good(hopefully) & more reagent code
  code/__DEFINES/reagents.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/plumbing/reaction_chamber.dm
  code/modules/plumbing/plumbers/acclimator.dm
  code/modules/plumbing/plumbers/reaction_chamber.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/reaction_agents_reagents.dm
Labels: Upstream PR Merged

#1101 [MIRROR] Makes the active sonar stop destroying the game
  code/modules/mod/modules/modules_security.dm
Labels: Upstream PR Merged

#1102 [MIRROR] Gives broken canisters a description
  code/game/objects/structures/fluff.dm
Labels: Upstream PR Merged

#1099 [MIRROR] Added a larger afro hairstyle
  code/datums/sprite_accessories.dm
  code/modules/client/preferences/species_features/basic.dm
  code/modules/clothing/head/wig.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/basic/space_fauna/ghost.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head_hair_and_lips.dm
  icons/mob/human/human_face.dmi
Labels: Upstream PR Merged

#1072 [MIRROR] [NO GBP] Some more code maintenance for reagents
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/plumbing/reaction_chamber.dm
  code/game/atoms.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/plumbing/plumbers/acclimator.dm
  code/modules/plumbing/plumbers/teleporter.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/reagents/reagent_containers/dropper.dm
Labels: Upstream PR Merged
